on:
  pull_request:
    branches: [ main , temp ]

env:
  ## Sets environment variable
   db_host: "localhost"
   db_name: "ems"
   db_username: "root"
   db_password: "Andy@1234"
   region: "US_EAST_1"
   metricsServerPort: 8125
   metricsServerHostname: localhost
   publishMetrics: true
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile code
      run: mvn compile
  test:
    runs-on: ubuntu-latest
    name: Running tests
    needs: compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run unit tests
        run: |
          mvn test
          
