
on:
  push:
    branches: [ main , temp ]
  
env:
  ## Sets environment variable
   db_host: "localhost"
   db_username: "root"
   db_name: "ems"
   db_password: "Andy@1234"
   region: "US_EAST_1"
   metricsServerPort: 8125
   metricsServerHostname: localhost
   publishMetrics: true
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

jobs:
  move:
    runs-on: ubuntu-latest
    name: Moving files
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Packaging code
        run: |
          mvn package
          cd ./target
          mkdir lambda-0.0.1-SNAPSHOT
          ls -all
          unzip lambda-0.0.1-SNAPSHOT.jar -d ./lambda-0.0.1-SNAPSHOT
          cd ~
          mkdir lib
          mv ./lambda-0.0.1-SNAPSHOT/BOOT-INF/lib/*.jar ./lib
          mv ./lambda-0.0.1-SNAPSHOT/BOOT-INF/classes/com/LogEvent.class ./
          ls -all
          zip -r csye6225-serverless-${{ github.sha }}.zip ./lib/*.jar ./LogEvent.class
          mv csye6225-serverless-${{ github.sha }}.zip ./
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      #- name: Packer build
      #  uses: ExitoLab/packer_build_action_aws@v0.2.10
      #  with:
      #    templateFile: 'ami.json'
      #    workingDir: 'ami'
      #  env:
      #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    AWS_DEFAULT_REGION: us-east-1
      #    SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
      #    SUBNET_ID: ${{ secrets.SUBNET_ID }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws lambda update-function-code --function-name csye6225-spring2022 --zip-file fileb://csye6225-serverless-${{ github.sha }}.zip

